default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] || 'mimo_api_development' %>
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  port: <%= ENV['POSTGRES_PORT'] || '5432' %>

test:
  <<: *default
  database: mimo_api_test
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] || '127.0.0.1' %>
  port: <%= ENV['TEST_POSTGRES_PORT'] || '5432' %>

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] || 'mimo-api' %>
  username: <%= ENV['POSTGRES_USER'] || 'mimo-api' %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host:     <%= ENV['POSTGRES_HOST'] || 'db' %>
